name: build on push
on: [push, workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          echo ***Updating Path***
          export PATH="$PATH:/home/githubactioner/.nvm/versions/node/v21.7.1/bin"
          echo $PATH
          whereis npm
          whereis node
          echo ***Moving to Project Repo***
          cd ~/my-website-vue
          echo ***Pulling***
          git pull
          echo ***Installing Node Modules***
          npm install
          echo ***Building Project***
          npm run build
          echo ***Updating Webpages***
          rm -rf /var/www/html
          cp -rT ~/my-website-vue/dist /var/www/html